services:
  mysql:
    image: mysql:9.5
    container_name: mysql-db  # Giving it a fixed name makes it easier
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  app:
    image: java-petclinic:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      # We use 'mysql-db' here because it matches the container_name above
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/petclinic
    depends_on:
      - mysql    
  
  #postgres:
  #  image: postgres:18.1
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    - POSTGRES_PASSWORD=petclinic
  #    - POSTGRES_USER=petclinic
  #    - POSTGRES_DB=petclinic
